imports:
    pyriemann.estimation:
        - ERPCovariances
    pyriemann.classification:
        - MDM
    utilities.dim_reduction:
        - RDR

pipeline:
    - ERPCovariances:
        estimator: 'oas'
        classes: [2]
    - RDR:
        n_components: 24
        method: 'nrme'
    - MDM:
        metric: 'riemann'

label: 'nrme (24) + mdm'