imports:
    pyriemann.estimation:
        - Covariances
    pyriemann.classification:
        - MDM
    utilities.dim_reduction:
        - RDR

pipeline:
    - Covariances:
        estimator: 'oas'
    - RDR:
        n_components: 36
        method: 'harandi-sup'
        params:
          nw: 22
          nb: 13
          approx: False
    - MDM:
        metric: 'riemann'

label: 'hrd-uns (36) + mdm'