imports:
    pyriemann.estimation:
        - Covariances
    pyriemann.classification:
        - MDM
    utilities.dim_reduction:
        - RDR

pipeline:
    - Covariances:
        estimator: 'oas'
    - RDR:
        n_components: 4
        method: 'nrme'
    - MDM:
        metric: 'riemann'

label: 'nrme (4) + mdm'