imports:
    pyriemann.estimation:
        - Covariances
    pyriemann.classification:
        - MDM
    utilities.dim_reduction:
        - RDR

pipeline:
    - Covariances:
        estimator: 'oas'
    - RDR:
        n_components: 24
        method: 'nrme-uns'
    - MDM:
        metric: 'riemann'

label: 'nrme-uns (24) + mdm'