imports:
    pyriemann.estimation:
        - Covariances
    pyriemann.classification:
        - MDM
    utilities.dim_reduction:
        - RDR

pipeline:
    - Covariances:
        estimator: 'lwf'
    - RDR:
        n_components: 24
        method: 'harandi-sup'
        params:
          nw: 20
          nb:  8
          approx: True
    - MDM:
        metric: 'riemann'

label: 'hrd-sup (24) + mdm'